---

- hosts: all
  become: true
  name: Deploy Docker onto your own server
  tasks:

  - name: Install prerequisite to use apt with https
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: Ensure Docker repository key is installed
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      id: "0EBFCD88"
      state: present
    ignore_errors: true

  - name: Ensure docker registry is available
    apt_repository: 
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Ensure docker and dependencies are installed
    apt:
      name: docker-ce
      update_cache: yes

  - name: Pick up participants
    include_vars:
      file: "group_vars/participants-addis.yml"

  - name: Allow unprivileged user to run docker
    user: 
      name: "{{ item.username }}"
      groups: docker
      append: yes
    with_items: "{{ participants }}"

